### PR TITLE
compat fixes for Julia v1.8

### PR DESCRIPTION
**Pull request by dkarrasch**
Depends on https://github.com/JuliaLang/julia/pull/41640/.

Needs to be adjusted regarding the exact DEV-version number.

### CODE REVIEW

**Comment by dkarrasch** [comment]
CI should be re-run in a few hours to make sure the tests run on a sufficiently up-to-date nightly version.

**Comment by palday** [comment]
@dkarrasch there's a doctest failure from a pivoted Cholesky being used where the non pivoted should be used. I've kicked off the CI again, but I'll take a closer look later if it fails.

**Review by palday — APPROVED** [review]
@dkarrasch thanks for handling this

**Comment by dkarrasch** [comment]
You're welcome!

**Pull request merged**
