### PR TITLE
Import df_residual

### PR DESCRIPTION
**Pull request by matthieugomez**
`df_residual` becomes a method from StatsBase if the following pull request is merged: https://github.com/JuliaStats/StatsBase.jl/pull/120

### CODE REVIEW

**Comment by Evizero** [comment]
same thing for `model_response`

**Comment by Evizero** [comment]
I know people got things to do and places to be, and that they do this in their spare time. 

But it is a bummer that I keep running into awesome Julia Packages like this all the time, where very simple PRs just like this one get no reaction whatsover and just sit there

**Comment by andreasnoack** [comment]
@matthieugomez Could you update this pr with an new version requirement for `StatsBase`? I've tagged a version of `StatsBase` after I merged your pull request.

**Comment by matthieugomez** [comment]
Thanks! It is failing but I'm not sure it's related to this pull request

**Comment by Evizero** [comment]
Could you include `model_response` to the import statement of StatsBase while your at it. I think there was an oversight and this seems to be a good PR to include it.

Concerning the build: I don't think it is related. I am having this precompilation issues as well on 0.4 with the current package state. I think I saw a issue about that yesterday but I can't seem to find it. It said something about updating to the newest 0.4 dev version if I recall correctly, but I didn't get around to try that yet

**Comment by andreasnoack** [comment]
Yes. Please also add `model_response`. I'll take a look at the error. It might be the binaries used for the testing that aren't up to date.

**Comment by matthieugomez** [comment]
All right. Also replaced some `StatsBase.fit` by `fit` since the function is imported.

**Comment by andreasnoack** [comment]
To avoid the procompilation error, I had to change the ordering in which the packages were loaded in the test file. Now lights are green so I'll merge. Thanks for the contribution and sorry about the delay.

**Comment by matthieugomez** [comment]
Thanks @Evizero and @andreasnoack

**Pull request merged**
