### PR TITLE
Fix tests on Julia 1.6

### PR DESCRIPTION
**Pull request by nalimilan**
`@sprintf` has been fixed to use two digits as requested, but existing
tests use a single digit.

### CODE REVIEW

**Review by kleinschmidt — APPROVED** [review]
If CI is happy I'm happy.  The Windows failures look unrelated to this but may be real failures?  I don't know well enough to say...

**Comment by nalimilan** [comment]
Funny that it happens only on Windows. The test is supposed to throw a `ConvergenceException` but for some reason it fails elsewhere. The error is similar to https://github.com/JuliaStats/GLM.jl/issues/224. Cc: @andreasnoack

**Comment by andreasnoack** [comment]
The line search fails. Something like ten iterations without improvement. It's indeed odd that it only happens on Windows. I'll run it a VM to see if I can reproduce it.

**Comment by andreasnoack** [comment]
I cannot reproduce this error on my Windows VM with 1.6.0.

**Pull request merged**
