### PR TITLE
Use StableRNG for testing

### PR DESCRIPTION
**Pull request by andreasnoack**
As noted in #433, tests are failing on nightly because of the RNG changes so I've switched from the default RNG to `StableRNG` to ensure stability across versions of Julia.

### CODE REVIEW

**Comment by andreasnoack** [comment]
I've added a commit that attempted to fix the failure on x86 Windows. It did fix a bug but the line search still fails. As mentioned elsewhere, I think that testing on x86 is a waste of our time. I don't have access to such a system and I doubt that any current users of this package run on x86 Windows. Hence, I'll suggest that we stop testing on x86 unless somebody steps up and offers to maintain the package for x86.

**Comment by andreasnoack** [comment]
I've added a commit that disables testing on x86

**Review by nalimilan — APPROVED** [review]
I'm a bit sad to stop testing 32-bit, but keeping it failing isn't better...

**Review by javier808 — CHANGES_REQUESTED** [review]
​name​: ​CI-future 
 ​on​: 
 ​  ​pull_request​: 
 ​    ​branches​: 
 ​      - ​master 
 ​  ​push​: 
 ​    ​branches​: 
 ​      - ​master 
 ​    ​tags​: ​'​*​' 
 ​jobs​: 
 ​  ​test​: 
 ​    ​name​: ​Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }} 
 ​    ​env​: 
 ​      ​JULIA_NUM_THREADS​: ​2 
 ​    ​runs-on​: ​${{ matrix.os }} 
 ​    ​strategy​: 
 ​      ​fail-fast​: ​false 
 ​      ​matrix​: 
 ​        ​version​: ​['nightly'] 
 ​        ​os​: ​['ubuntu-latest', 'macos-latest', 'windows-latest'] 
 ​        ​arch​: ​'​x64​' 
 ​    ​steps​: 
 ​      - ​run​: ​git config --global core.autocrlf false 
 ​      - ​uses​: ​actions/checkout@v2 
 ​      - ​uses​: ​julia-actions/setup-julia@v1 
 ​        ​with​: 
 ​          ​version​: ​${{ matrix.version }} 
 ​          ​arch​: ​${{ matrix.arch }} 
 ​      - ​uses​: ​actions/cache@v1 
 ​        ​env​: 
 ​          ​cache-name​: ​cache-artifacts 
 ​        ​with​: 
 ​          ​path​: ​~/.julia/artifacts 
 ​          ​key​: ​${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }} 
 ​          ​restore-keys​: ​| 
 ​            ${{ runner.os }}-test-${{ env.cache-name }}- 
 ​            ${{ runner.os }}-test- 
 ​            ${{ runner.os }}- 
 ​      - ​uses​: ​julia-actions/julia-buildpkg@v1 
 ​      - ​uses​: ​julia-actions/julia-runtest@v1      you taking my currency 💲💵 alert blocked

**Review by javier808 — CHANGES_REQUESTED** [review]
I got hacked help

**Pull request merged**
