### PR TITLE
Fixed linear model with perfectly collinear rhs variables and weights

### LINKED ISSUE #420: OLS with collinearity and weights
I am having a problem fitting an OLS model with weights and collinearity using GLM.jl.
Here is a simple example

```julia
y = rand(10)
x = rand(10, 2)
x = hcat(x,x)
lm(x,y) # correctly removes last two columns
lm(x, y, wts = ones(10)) # fails at cholesky! in GLM.delbeta!
lm(x, y, wts = ones(10), dropcollinear = true) # # fails at cholesky! in GLM.delbeta!
```

I further narrowed this down to the following function call:

```julia
linmod = LinearModel(GLM.LmResp(y,ones(10)), GLM.cholpred(x, true))
GLM.delbeta!(linmod.pp, linmod.rr.y, linmod.rr.wts) # fails
GLM.delbeta!(linmod.pp, linmod.rr.y) # works
```
using

```julia
@lessGLM.delbeta!(linmod.pp, linmod.rr.y, linmod.rr.wts)
```
I get

```julia
function delbeta!(p::DensePredChol{T,<:CholeskyPivoted}, r::Vector{T}, wt::Vector{T}) where T<:BlasReal
    cf = cholfactors(p.chol)
    piv = p.chol.p
    cf .= mul!(p.scratchm2, adjoint(LinearAlgebra.mul!(p.scratchm1, Diagonal(wt), p.X)), p.X)[piv, piv]
    cholesky!(Hermitian(cf, Symbol(p.chol.uplo)))
    ldiv!(p.chol, mul!(p.delbeta, transpose(p.scratchm1), r))
    p
end
```

and

```julia
@less GLM.delbeta!(linmod.pp, linmod.rr.y)
```

```julia
function delbeta!(p::DensePredChol{T,<:CholeskyPivoted}, r::Vector{T}) where T<:BlasReal
    ch = p.chol
    delbeta = mul!(p.delbeta, adjoint(p.X), r)
    rnk = rank(ch)
    if rnk == length(delbeta)
        ldiv!(ch, delbeta)
    else
        permute!(delbeta, ch.p)
        for k=(rnk+1):length(delbeta)
            delbeta[k] = -zero(T)
        end
        LAPACK.potrs!(ch.uplo, view(ch.factors, 1:rnk, 1:rnk), view(delbeta, 1:rnk))
        invpermute!(delbeta, ch.p)
    end
    p
end
```

Here is a naive implementation that seems to work:

```julia
using LinearAlgebra, GLM
y = rand(10)
x = rand(10, 2)
xc = hcat(x,x)
wts = [ones(5)..., 0.5 .* (ones(5))...];
```

```julia
T = eltype(xc)
ch = cholesky!((xc'diagm(wts)xc), Val(true), tol = -one(T), check = false) 
delbeta = zeros(T, size(xc,2))
delbeta = mul!(delbeta, adjoint(xc), diagm(wts)*y)
rnk = rank(ch)
permute!(delbeta, ch.p)
for k=(rnk+1):length(delbeta)
    delbeta[k] = -zero(Float64)
end
LAPACK.potrs!(ch.uplo, view(ch.factors, 1:rnk, 1:rnk), view(delbeta, 1:rnk))
invpermute!(delbeta, ch.p)
```

```julia
julia> delbeta[1:rnk] ≈ coef(lm(x, y, wts = wts))
true
```

### PR DESCRIPTION
**Pull request by dwinkler1**
This is my probably not very efficient suggestion to fix #420 
Suggestions very welcome!!

### CODE REVIEW

**Comment by danielw2904** [comment]
Please let me know if I should change anything in the PR. :)

**Comment by andreasnoack** [comment]
Looks right to me. Could you please add a test case as well?

**Comment by danielw2904** [comment]
I tried to add a teset but for me the earlier testset "linear model with weights" errors already. I feel like it is related to the PR but I am not sure how we even end up with a `CholeskyPivoted` in this case.

This would be my testset

```julia
@testset "collinearity and weights" begin
    rng = StableRNG(1234321)
    x1 = randn(100)
    x1_2 = 3 * x1
    x2 = 10 * randn(100)
    x2_2 = -2.4 * x2
    y = 1 .+ randn() * x1 + randn() * x2 + 2 * randn(100)
    df = DataFrame(y = y, x1 = x1, x2 = x1_2, x3 = x2, x4 = x2_2, weights = repeat([1, 0.5],50))
    f = @formula(y ~ x1 + x2 + x3 + x4)
    lm_model = lm(f, df, wts = df.weights)#, dropcollinear = true)
    X = [ones(length(y)) x1_2 x2_2]
    W = Diagonal(df.weights)
    coef_naive = (X'W*X)\X'W*y
    @test lm_model.model.pp.chol isa CholeskyPivoted
    @test rank(lm_model.model.pp.chol) == 3
    @test isapprox(filter(!=(0.0), coef(lm_model)), coef_naive)
end
```

This is what goes wrong earlier

```julia
julia>     lm_model = lm(f, df, wts = df.weights)
StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, CholeskyPivoted{Float64, Matrix{Float64}}}}, Matrix{Float64}}

FoodExp ~ 1 + Income

Coefficients:
──────────────────────────────────────────────────────────────────────────────
                     Coef.  Std. Error      t  Pr(>|t|)   Lower 95%  Upper 95%
──────────────────────────────────────────────────────────────────────────────
(Intercept)  -2794.53        2.92818e5  -0.01    0.9924  -5.77698e5  5.72109e5
Income           3.63222e6   3.36375e8   0.01    0.9914  -6.56787e8  6.64051e8
──────────────────────────────────────────────────────────────────────────────
```

**Comment by nalimilan** [comment]
> I tried to add a teset but for me the earlier testset "linear model with weights" errors already. I feel like it is related to the PR but I am not sure how we even end up with a `CholeskyPivoted` in this case.

We use `dropcollinear=true` by default, so you get a `CholeskyPivoted` unless you pass `dropcollinear=false` explicitly. From a quick check, it appears that the new failure is due to changes this PR makes for the `if rnk == length(ch.p)` case. Do you really need to change the code in that branch?

**Comment by danielw2904** [comment]
@nalimilan you were of course correct. I fixed that and added tests (all test passing now). However, I made a mess with autoformatting in vscode. What would be the best way to get just the stuff I changed in without the unnecessary indentation changes? Should I just fork again?
Sorry my experience with git pull requests is quite limited.

**Comment by nalimilan** [comment]
Thanks. There are still some failures which may well be random given that they happen on different versions. Any idea what may be going on? Can you reproduce these locally?

**Comment by danielw2904** [comment]
Looks like numeric instability to me. I'll investigate. Maybe I can write a more stable version of the test case.

**Comment by nalimilan** [comment]
Bump. Maybe try a different set of values?

**Comment by alecloudenback** [comment]
Bump on this PR. I am encountering the issue in #420 as well. 

On my local machine (1.8RC4, Mac M1) the tests pass. I agree with @danielw2904 that this appears to just be a numerical difference which stands out because the failing tests were printing `+/- 0.0...`

All four failing test cases in the `F test for model comparison` testset were a change in +/- 0.0, for example:


https://user-images.githubusercontent.com/711879/184523051-af00bf9a-96c5-4785-b0b5-69229b78d727.mov

**Comment by danielw2904** [comment]
Sorry, I am unable to work on this anymore.

**Comment by nalimilan** [comment]
Unfortunately it seems to me that something more serious is going on. Locally, tests always fail, even on Julia 1.7. Maybe this has to do with BLAS and the CPU? The following models give completely different coefficients here:
```julia
julia> using GLM, StableRNGs

julia> rng = StableRNG(1234321);

julia> x1 = randn(rng, 100);

julia> x1_2 = 3 * x1;

julia> x2 = 10 * randn(rng, 100);

julia> x2_2 = -2.4 * x2;

julia> y = 1 .+ randn(rng) * x1 + randn(rng) * x2 + 2 * randn(rng, 100);

julia> df = DataFrame(y = y, x1 = x1, x2 = x1_2, x3 = x2, x4 = x2_2, weights = repeat([1, 0.5],50));

julia> lm_collinear = lm(@formula(y ~ x1 + x2 + x3 + x4), df, wts=df.weights)
StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, CholeskyPivoted{Float64, Matrix{Float64}}}}, Matrix{Float64}}

y ~ 1 + x1 + x2 + x3 + x4

Coefficients:
───────────────────────────────────────────────────────────────────────────
                  Coef.  Std. Error       t  Pr(>|t|)  Lower 95%  Upper 95%
───────────────────────────────────────────────────────────────────────────
(Intercept)  0.00389006    7.74397     0.00    0.9996  -15.4334    15.4412
x1           0.0         NaN         NaN       NaN     NaN        NaN
x2           0.594857      2.78844     0.21    0.8317   -4.96379    6.1535
x3           0.0         NaN         NaN       NaN     NaN        NaN
x4           4.11564       0.351608   11.71    <1e-17    3.41472    4.81656
───────────────────────────────────────────────────────────────────────────

julia> lm_reduced = lm(@formula(y ~ x2 + x4), df, wts=df.weights)
StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, CholeskyPivoted{Float64, Matrix{Float64}}}}, Matrix{Float64}}

y ~ 1 + x2 + x4

Coefficients:
────────────────────────────────────────────────────────────────────────
                Coef.  Std. Error      t  Pr(>|t|)  Lower 95%  Upper 95%
────────────────────────────────────────────────────────────────────────
(Intercept)  1.29678    0.265978    4.88    <1e-05  0.766565    1.827
x2           0.215149   0.0973285   2.21    0.0302  0.0211286   0.40917
x4           0.648579   0.0124034  52.29    <1e-58  0.623853    0.673305
────────────────────────────────────────────────────────────────────────

julia> deviance(lm_collinear)
410484.4884591147

julia> deviance(lm_reduced)
355.2246843374244
```

On current master, both models have the same deviance and the same predictions, so it seems that this PR introduces a regression at least in some cases.

**Comment by nalimilan** [comment]
Though if https://github.com/JuliaStats/GLM.jl/pull/487#issuecomment-1214433562 fixes it, then maybe we don't need this PR after all?

**Comment by andreasnoack** [comment]
It looks like this was fixed by another PR, see https://github.com/JuliaStats/GLM.jl/issues/420#issuecomment-2490461084.

**Pull request closed without merging**
