### PR TITLE
Set minimum Julia version to 1.6

### PR DESCRIPTION
**Pull request by ararslan**
Currently the minimum version is 1.0, which is old and unsupported and makes development and addition of new features more difficult. I suspect this won't be too controversial.

### CODE REVIEW

**Review by bkamins — APPROVED** [review]
maybe add nightly to CI?

**Comment by ararslan** [comment]
Nightly is already in CI as the "CI-future" jobs

**Comment by bkamins** [comment]
ah - OK. In DataFrames.jl we have a bit different structure of CI file and I looked only at diff.

**Comment by ararslan** [comment]
Yeah the CI structure for this package is kind of strange, could be worth standardizing it at some point.

**Comment by ararslan** [comment]
I fixed the main CI failure on nightly, the nightly failure on Windows is unrelated and related to building TimeZones.

**Pull request merged**
